user:
  class: '\Bormborm\Controller\MainController'
  method: 'getUser'

comment:
  class: '\Bormborm\Controller\MainController'
  method: 'getComment'

post:
  class: '\Bormborm\Controller\MainController'
  method: 'getPost'

index:
  class: '\Bormborm\Controller\MainController'
  method: 'index'

logout:
  class: '\Bormborm\Controller\MainController'
  method: 'index'

login:
  class: '\Bormborm\Controller\AuthController'
  method: 'login'

register:
  class: '\Bormborm\Controller\AuthController'
  method: 'register'

addPost:
  class: '\Bormborm\Controller\MainController'
  method: 'addPost'

deletePost:
  class: '\Bormborm\Controller\MainController'
  method: 'deletePost'

addComment:
  class: '\Bormborm\Controller\MainController'
  method: 'addComment'

deleteComment:
  class: '\Bormborm\Controller\MainController'
  method: 'deleteComment'

