user:
  class: '\Bormborm\Controller\MainController'
  method: 'getUser'

comment:
  class: '\Bormborm\Controller\MainController'
  method: 'getComment'

post:
  class: '\Bormborm\Controller\MainController'
  method: 'getPost'

index:
  class: '\Bormborm\Controller\MainController'
  method: 'index'

logout:
  class: '\Bormborm\Controller\MainController'
  method: 'index'

login:
  class: '\Bormborm\Controller\MainController'
  method: 'login'
